<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>《干货！IT小伙伴们实用的网站及工具大集合！持续更新！》的评论</title>
	<atom:link href="http://cuiqingcai.com/455.html/feed" rel="self" type="application/rss+xml" />
	<link>http://cuiqingcai.com/455.html</link>
	<description>静静寻觅生活的美好</description>
	<lastBuildDate>Thu, 11 Feb 2016 23:10:24 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://wordpress.org/?v=4.2.5</generator>
	<item>
		<title>作者：林贞恩</title>
		<link>http://cuiqingcai.com/455.html/comment-page-1#comment-1186</link>
		<dc:creator><![CDATA[林贞恩]]></dc:creator>
		<pubDate>Sun, 24 Jan 2016 22:51:58 +0000</pubDate>
		<guid isPermaLink="false">http://cuiqingcai.com/?p=455#comment-1186</guid>
		<description><![CDATA[鉴定完毕！]]></description>
		<content:encoded><![CDATA[<p>鉴定完毕！</p>
]]></content:encoded>
	</item>
	<item>
		<title>作者：乐儿</title>
		<link>http://cuiqingcai.com/455.html/comment-page-1#comment-1134</link>
		<dc:creator><![CDATA[乐儿]]></dc:creator>
		<pubDate>Sun, 03 Jan 2016 03:26:47 +0000</pubDate>
		<guid isPermaLink="false">http://cuiqingcai.com/?p=455#comment-1134</guid>
		<description><![CDATA[很久没来了，过来看看]]></description>
		<content:encoded><![CDATA[<p>很久没来了，过来看看</p>
]]></content:encoded>
	</item>
	<item>
		<title>作者：乐儿</title>
		<link>http://cuiqingcai.com/455.html/comment-page-1#comment-1133</link>
		<dc:creator><![CDATA[乐儿]]></dc:creator>
		<pubDate>Sun, 03 Jan 2016 03:26:25 +0000</pubDate>
		<guid isPermaLink="false">http://cuiqingcai.com/?p=455#comment-1133</guid>
		<description><![CDATA[　　小区有位美女开了家动物诊所，我和一哥们忍不住去搭讪：你好，请问这里是给动物看病的吗？
　　她微笑着回答：是的！
　　哥们抢先一步躺在了病床上：请给我检查一下，我是程序猿！
　　我不甘示弱，立即紧挨着他躺下：也请给我检查检查，我是单身狗！]]></description>
		<content:encoded><![CDATA[<p>　　小区有位美女开了家动物诊所，我和一哥们忍不住去搭讪：你好，请问这里是给动物看病的吗？<br />
　　她微笑着回答：是的！<br />
　　哥们抢先一步躺在了病床上：请给我检查一下，我是程序猿！<br />
　　我不甘示弱，立即紧挨着他躺下：也请给我检查检查，我是单身狗！</p>
]]></content:encoded>
	</item>
	<item>
		<title>作者：干货！IT小伙伴们实用的网站及工具大集合！持续更新！ &#124; 大笨猪的小屋</title>
		<link>http://cuiqingcai.com/455.html/comment-page-1#comment-1286</link>
		<dc:creator><![CDATA[干货！IT小伙伴们实用的网站及工具大集合！持续更新！ &#124; 大笨猪的小屋]]></dc:creator>
		<pubDate>Sat, 26 Sep 2015 10:26:25 +0000</pubDate>
		<guid isPermaLink="false">http://cuiqingcai.com/?p=455#comment-1286</guid>
		<description><![CDATA[[&#8230;] 原文链接：静觅 ? 干货！IT小伙伴们实用的网站及工具大集合！持续更新！ [&#8230;]]]></description>
		<content:encoded><![CDATA[<p>[&#8230;] 原文链接：静觅 ? 干货！IT小伙伴们实用的网站及工具大集合！持续更新！ [&#8230;]</p>
]]></content:encoded>
	</item>
	<item>
		<title>作者：干货！IT小伙伴们实用的网站及工具大集合！持续更新！ &#124; 大笨猪的小屋</title>
		<link>http://cuiqingcai.com/455.html/comment-page-1#comment-858</link>
		<dc:creator><![CDATA[干货！IT小伙伴们实用的网站及工具大集合！持续更新！ &#124; 大笨猪的小屋]]></dc:creator>
		<pubDate>Sat, 26 Sep 2015 02:26:25 +0000</pubDate>
		<guid isPermaLink="false">http://cuiqingcai.com/?p=455#comment-858</guid>
		<description><![CDATA[[&#8230;] 原文链接：静觅 » 干货！IT小伙伴们实用的网站及工具大集合！持续更新！ [&#8230;]]]></description>
		<content:encoded><![CDATA[<p>[&#8230;] 原文链接：静觅 » 干货！IT小伙伴们实用的网站及工具大集合！持续更新！ [&#8230;]</p>
]]></content:encoded>
	</item>
	<item>
		<title>作者：南国掌柜</title>
		<link>http://cuiqingcai.com/455.html/comment-page-1#comment-857</link>
		<dc:creator><![CDATA[南国掌柜]]></dc:creator>
		<pubDate>Fri, 25 Sep 2015 02:00:17 +0000</pubDate>
		<guid isPermaLink="false">http://cuiqingcai.com/?p=455#comment-857</guid>
		<description><![CDATA[整合得不错~]]></description>
		<content:encoded><![CDATA[<p>整合得不错~</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.087 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-02-11 23:31:07 -->
